-- Active: 1728650081456@@127.0.0.1@3306@demo2
CREATE TABLE users(
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
    firstname VARCHAR(50) NOT NULL,
    lastname VARCHAR (50) NOT NULL,
    email VARCHAR(50) NOT NULL,
    password VARCHAR (500) NOT NULL,
    phone VARCHAR (20) NOT NULL,
    otp VARCHAR (6) NOT NULL DEFAULT '0',
    creat_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP(),
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP() ON UPDATE CURRENT_TIMESTAMP() 
)

-- create categories

CREATE TABLE categories(
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR (50) NOT NULL,
    user_id BIGINT UNSIGNED NOT NULL,
    Foreign Key (`user_id`) REFERENCES users (`id`) ON DELETE RESTRICT ON UPDATE CASCADE,
    create_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP(),
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP() ON UPDATE CURRENT_TIMESTAMP()
)

-- create product 

CREATE TABLE products(
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR (50) NOT NULL,
    price VARCHAR (10) NOT NULL,
    unit VARCHAR (10) NOT NULL,
    discription TEXT NOT NULL,
    categories_id BIGINT UNSIGNED NOT NULL,
    user_id BIGINT UNSIGNED NOT NULL,
    Foreign Key (`categories_id`) REFERENCES categories (`id`) ON DELETE RESTRICT ON UPDATE CASCADE,
    Foreign Key (`user_id`) REFERENCES users (`id`) ON DELETE RESTRICT ON UPDATE CASCADE,
    create_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP(),
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP() ON UPDATE CURRENT_TIMESTAMP()   
)

-- create customer

CREATE TABLE customers(
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR (50) NOT NULL,
    phone VARCHAR (20) NOT NULL,
    email VARCHAR(50) NOT NULL,
    user_id BIGINT UNSIGNED NOT NULL,
    Foreign Key (`user_id`) REFERENCES users (`id`) ON DELETE RESTRICT ON UPDATE CASCADE,
    create_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP(),
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP() ON UPDATE CURRENT_TIMESTAMP()
)
