-- Active: 1728650081456@@127.0.0.1@3306@demo2
CREATE TABLE users(
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
    firstname VARCHAR(50) NOT NULL,
    lastname VARCHAR (50) NOT NULL,
    email VARCHAR(50) NOT NULL,
    password VARCHAR (500) NOT NULL,
    phone VARCHAR (20) NOT NULL,
    otp VARCHAR (6) NOT NULL DEFAULT '0',
    creat_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP(),
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP() ON UPDATE CURRENT_TIMESTAMP() 
)

-- create categories table

CREATE TABLE categories(
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR (50) NOT NULL,
    user_id BIGINT UNSIGNED NOT NULL,
    Foreign Key (`user_id`) REFERENCES users (`id`) ON DELETE RESTRICT ON UPDATE CASCADE,
    create_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP(),
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP() ON UPDATE CURRENT_TIMESTAMP()
)

-- create product  table

CREATE TABLE products(
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR (50) NOT NULL,
    price VARCHAR (10) NOT NULL,
    unit VARCHAR (10) NOT NULL,
    discription TEXT NOT NULL,
    categories_id BIGINT UNSIGNED NOT NULL,
    user_id BIGINT UNSIGNED NOT NULL,
    Foreign Key (`categories_id`) REFERENCES categories (`id`) ON DELETE RESTRICT ON UPDATE CASCADE,
    Foreign Key (`user_id`) REFERENCES users (`id`) ON DELETE RESTRICT ON UPDATE CASCADE,
    create_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP(),
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP() ON UPDATE CURRENT_TIMESTAMP()   
)

-- create customer table

CREATE TABLE customers(
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR (50) NOT NULL,
    phone VARCHAR (20) NOT NULL,
    email VARCHAR(50) NOT NULL,
    user_id BIGINT UNSIGNED NOT NULL,
    Foreign Key (`user_id`) REFERENCES users (`id`) ON DELETE RESTRICT ON UPDATE CASCADE,
    create_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP(),
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP() ON UPDATE CURRENT_TIMESTAMP()
)

-- create invoise table

CREATE TABLE invoices(
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
    total VARCHAR (10) NOT NULL,
    discout VARCHAR (10) NOT NULL,
    vat VARCHAR (10) NOT NULL,
    total_payable VARCHAR (10) NOT NULL,
    user_id BIGINT UNSIGNED NOT NULL,
    Foreign Key (`user_id`) REFERENCES users (`id`) ON DELETE RESTRICT ON UPDATE CASCADE,
    customer_id BIGINT UNSIGNED NOT NULL,
    Foreign Key (`customer_id`) REFERENCES customers (`id`) ON DELETE RESTRICT ON UPDATE CASCADE,
    create_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP(),
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP() ON UPDATE CURRENT_TIMESTAMP()
)

-- create invoice_items table

CREATE TABLE invoice_items(
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
    quantity VARCHAR (10) NOT NULL,
    price VARCHAR (10) NOT NULL,
    product_id BIGINT UNSIGNED NOT NULL,
    Foreign Key (`product_id`) REFERENCES products (`id`) ON DELETE RESTRICT ON UPDATE CASCADE,
    invoice_id BIGINT UNSIGNED NOT NULL,
    Foreign Key (`invoice_id`) REFERENCES invoices (`id`) ON DELETE RESTRICT ON UPDATE CASCADE,
    user_id BIGINT UNSIGNED NOT NULL,
    Foreign Key (`user_id`) REFERENCES users (`id`) ON DELETE RESTRICT ON UPDATE CASCADE,
    create_at  TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP(),
    update_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP() ON UPDATE CURRENT_TIMESTAMP()
)